spring:
  application:
    name: merchants
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_plus?autoReconnect=true&useSSL=false
    username: root
    password: root
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: coupon-plus
    listener:
      concurrency: 4

server:
  port: 8089

logging:
  level: debug
  file: merchants.log

